<<<<<<< Updated upstream
# Generated by Django 3.2.15 on 2022-11-05 19:15

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='meals',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='hostel',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
=======
# Generated by Django 3.2.15 on 2022-11-05 19:15

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='meals',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='hostel',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
>>>>>>> Stashed changes
